'use client';

import { useRouter } from 'next/navigation';
import { useSession } from 'next-auth/react';
import { PageContainer } from '@/components/shared/PageContainer';
import { Button } from '@/components/ui/Button';
import { Sparkles, BrainCircuit, ShieldCheck, Target, ArrowRight } from 'lucide-react';

export default function Home() {
  const router = useRouter();
  const { status } = useSession();

  const handleGetStarted = () => {
    if (status === 'authenticated') {
      router.push('/dashboard');
    } else {
      router.push('/signup');
    }
  };

  return (
    <div className="min-h-[calc(100vh-73px)] relative overflow-hidden bg-[#0B0F17]">
      {/* Background Orbs */}
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-slate-400/10 blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full bg-slate-300/10 blur-[120px] pointer-events-none" />

      <PageContainer className="relative z-10 pt-20 pb-32">
        {/* 1. Hero Section */}
        <div className="text-center max-w-4xl mx-auto mb-24 animate-in fade-in slide-in-from-bottom-8 duration-1000">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/[0.03] border border-white/[0.08] mb-8">
            <Sparkles className="w-4 h-4 text-slate-300" />
            <span className="text-sm font-medium text-slate-300">Powered by Groq AI Insights</span>
          </div>
          
          <h1 className="text-6xl md:text-8xl font-black tracking-tight mb-8 leading-[1.1]">
            <span className="text-white">Plan Your Money</span>
            <br />
            <span className="text-slate-300">Smarter.</span>
          </h1>
          
          <p className="text-xl md:text-2xl text-slate-400 max-w-2xl mx-auto mb-10 leading-relaxed font-light">
            Set goals, optimize taxes, and grow your wealth with intelligent, automated financial planning.
          </p>
          
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Button
              onClick={handleGetStarted}
              className="w-full sm:w-auto h-14 px-10 text-lg bg-white hover:bg-slate-200 text-[#0A0D14] rounded-full shadow-[0_0_30px_rgba(255,255,255,0.15)] transition-all duration-300 hover:scale-105 font-semibold"
            >
              {status === 'authenticated' ? 'Go to Dashboard' : 'Get Started Free'}
              <ArrowRight className="ml-2 w-5 h-5" />
            </Button>
            {status !== 'authenticated' && (
              <Button
                onClick={() => router.push('/login')}
                variant="outline"
                className="w-full sm:w-auto h-14 px-10 text-lg bg-white/[0.03] border-white/[0.1] text-white hover:bg-white/[0.08] rounded-full transition-all duration-300"
              >
                Log In
              </Button>
            )}
          </div>
        </div>

        {/* 2. Features Section */}
        <div className="grid md:grid-cols-3 gap-6 mb-32">
          {[
            {
              icon: Target,
              title: 'Smart Planning',
              desc: 'Automatically route your savings into optimized buckets to reach your life goals faster.',
              color: 'text-slate-200',
              bg: 'bg-white/[0.05]'
            },
            {
              icon: ShieldCheck,
              title: 'Tax Optimization',
              desc: 'Advanced Indian tax regime comparisons utilizing 80C deductions to maximize your take-home pay.',
              color: 'text-slate-300',
              bg: 'bg-white/[0.05]'
            },
            {
              icon: BrainCircuit,
              title: 'AI Insights',
              desc: 'Get human-readable, personalized financial advice generated by lightning-fast Groq AI.',
              color: 'text-slate-400',
              bg: 'bg-white/[0.05]'
            }
          ].map((feature, i) => (
            <div key={i} className="glass-card glass-card-hover rounded-3xl p-8 text-left transition-all duration-500 group">
              <div className={`w-14 h-14 rounded-2xl ${feature.bg} flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-300`}>
                <feature.icon className={`w-7 h-7 ${feature.color}`} />
              </div>
              <h3 className="text-2xl font-bold text-white mb-3">{feature.title}</h3>
              <p className="text-slate-400 leading-relaxed">
                {feature.desc}
              </p>
            </div>
          ))}
        </div>

        {/* 3. How It Works / CTA Section */}
        <div className="relative rounded-[2.5rem] overflow-hidden p-12 md:p-20 text-center glass-card border-white/[0.1]">
          <div className="absolute inset-0 bg-white/[0.02]" />
          <div className="relative z-10 max-w-3xl mx-auto">
            <h2 className="text-4xl md:text-5xl font-black text-white mb-6 tracking-tight">
              Ready to take control?
            </h2>
            <p className="text-xl text-slate-300 mb-10 font-light">
              Join thousands of users who have already optimized their financial future. No hidden fees. 100% secure.
            </p>
            <Button
              onClick={handleGetStarted}
              className="h-14 px-12 text-lg bg-white text-[#0B0F17] hover:bg-slate-200 rounded-full font-bold shadow-[0_0_30px_rgba(255,255,255,0.2)] transition-all duration-300 hover:scale-105"
            >
              Start Planning Now
            </Button>
          </div>
        </div>

      </PageContainer>
    </div>
  );
}
